[package]
name = "flat-blend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lyon = "1.0.1"
miniquad = "0.3.15"
quad-rand = "0.2.1"
